;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        smex
        wgrep-change-to-wgrep-mode
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-semi&comma
        c-electric-slash
        paredit-forward-delete
        read-only-mode
        sp--self-insert-command
        undefined
        ))
