;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	c-electric-semi&comma
	electric-newline-and-maybe-indent
	end-of-visual-line
	kill-region
	kill-visual-line
	smex
	sp--self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	))
