;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	abort-recursive-edit
	beginning-of-visual-line
	c-electric-brace
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	end-of-visual-line
	ido-switch-buffer
	kill-region
	kill-visual-line
	org-ctrl-c-minus
	org-delete-char
	paredit-forward-delete
	paredit-newline
	smex
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	))
